"""
Django settings for mlops_django project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ENV
env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = env.bool("DJANGO_DEBUG", default=False)

# boş bırakılırsa [] olsun
_allowed_hosts = env("DJANGO_ALLOWED_HOSTS", default="")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]

# Application definition
INSTALLED_APPS = [
    "django_celery_results",
    "workflow",
    "rest_framework",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mlops_django.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mlops_django.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME", default="mlops_db"),
        "USER": env("DB_USER", default="mlops_user"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST", default="localhost"),
        "PORT": env("DB_PORT", default="5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------------------
# CELERY
# -------------------------
# Tek kaynak: .env (default verildi, projeyi bozmaz)
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="amqp://localhost")
CELERY_RESULT_BACKEND = "django-db"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = "Europe/Istanbul"

CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True

# --- Celery queue görünürlüğü için önerilenler ---
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TRACK_STARTED = True

DEBUG_STEP_DELAY_SEC = env.float("DEBUG_STEP_DELAY_SEC", default=0.5)

# -------------------------
# RABBITMQ MANAGEMENT (15672)
# -------------------------
RABBITMQ_API_URL = env("RABBITMQ_API_URL", default="http://127.0.0.1:15672/api")
RABBITMQ_USER = env("RABBITMQ_USER", default="guest")
RABBITMQ_PASS = env("RABBITMQ_PASS", default="guest")
RABBITMQ_VHOST = env("RABBITMQ_VHOST", default="/")
RABBITMQ_DEFAULT_QUEUE = env("RABBITMQ_DEFAULT_QUEUE", default="celery")
RABBITMQ_TIMEOUT = env.int("RABBITMQ_TIMEOUT", default=5)

# queue_client.py'nin beklediği format
RABBITMQ_MANAGEMENT = {
    "URL": RABBITMQ_API_URL.rsplit("/api", 1)[0],  # "http://127.0.0.1:15672"
    "USERNAME": RABBITMQ_USER,
    "PASSWORD": RABBITMQ_PASS,
    "VHOST": RABBITMQ_VHOST,
    "QUEUE_NAME": RABBITMQ_DEFAULT_QUEUE,
}
# -------------------------
# Project Paths (datasets/models) - runtime oluşturma
# -------------------------
DATASETS_DIR = BASE_DIR / "datasets"
PROCESSED_DIR = DATASETS_DIR / "processed"
MODELS_DIR = BASE_DIR / "models"

for p in [DATASETS_DIR, PROCESSED_DIR, MODELS_DIR]:
    p.mkdir(parents=True, exist_ok=True)
