# Generated by Django 5.0.8 on 2025-07-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_workflowstep_celery_task_id_workflowstep_task_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowstep",
            name="celery_task_id",
        ),
        migrations.RemoveField(
            model_name="workflowstep",
            name="task_result",
        ),
    ]
