# Generated by Django 5.0.8 on 2025-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0003_remove_workflowstep_celery_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Celery TaskResult.task_id ile ilişki",
                max_length=255,
                null=True,
            ),
        ),
    ]
